name: app_comarcas
description: "Aplicación de flutter que trata de dar información sobre las provincias de la comunidad valencia y sus comarcas."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
  - assets/logo.png
  - assets/logoIes.png
  - assets/clima.png
  - assets/2x/logo.png
  - assets/3x/logo.png

  fonts:
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf

